import Foundation
import Testing
@testable import Incur

private struct TypegenNoopHandler: CommandHandler, Sendable {
    func run(_ ctx: CommandContext) async -> CommandResult { .ok(data: .null) }
}

@Suite("Typegen")
struct TypegenTests {

    @Test func generateFromCliWithTwoCommandsContainsExpectedTypeNames() {
        let cli = Cli("test")
            .command("get", CommandDef(
                name: "get",
                argsFields: [FieldMeta(name: "id", fieldType: .number, required: true)],
                handler: TypegenNoopHandler()
            ))
            .command("list", CommandDef(
                name: "list",
                optionsFields: [FieldMeta(name: "limit", fieldType: .number)],
                handler: TypegenNoopHandler()
            ))

        let source = generateSwiftSource(cli: cli)

        // Header
        #expect(source.contains("// Generated by IncurGen"))
        #expect(source.contains("import Incur"))
        #expect(source.contains("public enum IncurGenerated"))
        #expect(source.contains("public static let cliName = \"test\""))

        // Per-command typed structs
        #expect(source.contains("public enum Get"))
        #expect(source.contains("public enum List"))
        #expect(source.contains("public static let name = \"get\""))
        #expect(source.contains("public static let name = \"list\""))

        // Helper function for each
        #expect(source.contains("public static func cta("))

        // Args+options typed
        #expect(source.contains("id: Double"))
        #expect(source.contains("limit: Double? = nil"))
    }

    @Test func ctaBuilderIncludesArgsAndOptions() {
        let cli = Cli("test").command("add", CommandDef(
            name: "add",
            argsFields: [FieldMeta(name: "title", fieldType: .string, required: true)],
            optionsFields: [
                FieldMeta(name: "priority", fieldType: .string),
            ],
            handler: TypegenNoopHandler()
        ))

        let source = generateSwiftSource(cli: cli)
        #expect(source.contains("public enum Add"))
        // Body should include the command name and field interpolation
        #expect(source.contains("var parts: [String] = [\"add\"]"))
        #expect(source.contains("parts.append(\"\\(title)\")"))
        #expect(source.contains("parts.append(\"--priority \\(v)\")"))
    }

    @Test func nestedCommandsUseFullPath() {
        let cli = Cli("test")
        let listCmd = CommandDef(name: "list", handler: TypegenNoopHandler())
        let createCmd = CommandDef(
            name: "create",
            argsFields: [FieldMeta(name: "title", fieldType: .string, required: true)],
            handler: TypegenNoopHandler()
        )
        cli.commands["pr"] = .group(
            description: "PR commands",
            commands: [
                "list": .leaf(listCmd),
                "create": .leaf(createCmd),
            ],
            middleware: [],
            outputPolicy: nil
        )

        let source = generateSwiftSource(cli: cli)
        #expect(source.contains("public static let name = \"pr list\""))
        #expect(source.contains("public static let name = \"pr create\""))
        #expect(source.contains("public enum PrList"))
        #expect(source.contains("public enum PrCreate"))
    }

    @Test func emptyCliEmitsValidShell() {
        let cli = Cli("empty")
        let source = generateSwiftSource(cli: cli)
        #expect(source.contains("public enum IncurGenerated"))
        #expect(source.contains("public static let cliName = \"empty\""))
        #expect(source.contains("// No registered commands."))
    }

    @Test func generateFromManifestProducesEquivalentOutput() {
        let manifest: JSONValue = [
            "name": "test",
            "commands": [
                [
                    "name": "get",
                    "argsFields": [
                        [
                            "name": "id",
                            "type": "number",
                            "required": true,
                        ],
                    ],
                    "optionsFields": [],
                ],
                [
                    "name": "list",
                    "argsFields": [],
                    "optionsFields": [
                        [
                            "name": "limit",
                            "type": "number",
                        ],
                    ],
                ],
            ],
        ]

        let source = generateSwiftSource(manifest: manifest)
        #expect(source != nil)
        #expect(source!.contains("public enum Get"))
        #expect(source!.contains("public enum List"))
        #expect(source!.contains("id: Double"))
        #expect(source!.contains("limit: Double? = nil"))
    }

    @Test func generateFromInvalidManifestReturnsNil() {
        let bad: JSONValue = ["foo": "bar"]
        #expect(generateSwiftSource(manifest: bad) == nil)
    }

    @Test func commandsAreSortedAlphabetically() {
        let cli = Cli("test")
            .command("zebra", CommandDef(name: "zebra", handler: TypegenNoopHandler()))
            .command("alpha", CommandDef(name: "alpha", handler: TypegenNoopHandler()))
            .command("middle", CommandDef(name: "middle", handler: TypegenNoopHandler()))

        let source = generateSwiftSource(cli: cli)
        let alphaIdx = source.range(of: "public enum Alpha")?.lowerBound
        let middleIdx = source.range(of: "public enum Middle")?.lowerBound
        let zebraIdx = source.range(of: "public enum Zebra")?.lowerBound
        #expect(alphaIdx != nil && middleIdx != nil && zebraIdx != nil)
        if let a = alphaIdx, let m = middleIdx, let z = zebraIdx {
            #expect(a < m && m < z)
        }
    }

    @Test func swiftKeywordsAreEscaped() {
        // A field literally named "class" should be backtick-escaped.
        let cli = Cli("test").command("foo", CommandDef(
            name: "foo",
            argsFields: [FieldMeta(name: "class", fieldType: .string, required: true)],
            handler: TypegenNoopHandler()
        ))
        let source = generateSwiftSource(cli: cli)
        #expect(source.contains("`class`: String"))
    }
}
