/// Codegen for typed Swift CTA helpers from a registered CLI.
///
/// Mirrors the TS `Typegen` module (incurs/src/Typegen.ts), adapted for Swift.
/// Where TS emits a `.d.ts` module augmentation with typed `args` and `options`,
/// Swift emits a single source file (`Incur.generated.swift`) containing one
/// nested struct per leaf command. Each generated struct carries the command
/// name and a `cta(...)` function that builds an invocation string with typed
/// parameters — useful for downstream consumers building `CtaBlock`s.
///
/// The generator uses string templating only (no swift-syntax) so consumers
/// don't pay the swift-syntax dependency cost.

import Foundation

// MARK: - Public API

/// Generates `Incur.generated.swift` source for a `Cli` instance.
///
/// Walks the command tree, flattens leaves with their full dotted path, and
/// emits one nested type per command with typed `args`/`options` and a `cta`
/// builder.
public func generateSwiftSource(cli: Cli) -> String {
    let entries = collectTypegenEntries(commands: cli.commands)
        .sorted { $0.fullName < $1.fullName }
    return renderSwiftSource(cliName: cli.name, entries: entries)
}

/// Generates Swift source from a JSON manifest produced by `<cli> --llms-full`
/// or any equivalent serialization of `SkillCommandInfo`. Mirrors the TS
/// `Typegen.generate(input, output)` flow which imports a CLI module then
/// generates types.
///
/// Manifest shape (matches `skillGenerate` output, simplified):
/// ```
/// {
///   "name": "todoapp",
///   "commands": [
///     { "name": "add", "argsFields": [...], "optionsFields": [...] }
///   ]
/// }
/// ```
public func generateSwiftSource(manifest: JSONValue) -> String? {
    guard let cliName = manifest["name"]?.stringValue else { return nil }
    guard let cmds = manifest["commands"]?.arrayValue else { return nil }

    let entries = cmds.compactMap { entry -> TypegenEntry? in
        guard let name = entry["name"]?.stringValue else { return nil }
        let argsFields = parseFieldArray(entry["argsFields"]?.arrayValue ?? [])
        let optionsFields = parseFieldArray(entry["optionsFields"]?.arrayValue ?? [])
        return TypegenEntry(
            fullName: name,
            argsFields: argsFields,
            optionsFields: optionsFields
        )
    }
    .sorted { $0.fullName < $1.fullName }

    return renderSwiftSource(cliName: cliName, entries: entries)
}

// MARK: - Internal Types

struct TypegenEntry {
    let fullName: String
    let argsFields: [FieldMeta]
    let optionsFields: [FieldMeta]
}

// MARK: - Collection

func collectTypegenEntries(
    commands: [String: CommandEntry],
    prefix: [String] = []
) -> [TypegenEntry] {
    var result: [TypegenEntry] = []
    for (name, entry) in commands {
        let path = prefix + [name]
        switch entry {
        case .leaf(let def):
            result.append(TypegenEntry(
                fullName: path.joined(separator: " "),
                argsFields: def.argsFields,
                optionsFields: def.optionsFields
            ))
        case .group(_, let subs, _, _):
            result.append(contentsOf: collectTypegenEntries(commands: subs, prefix: path))
        case .fetchGateway:
            // Fetch gateways have no static schema — skip.
            break
        }
    }
    return result
}

// MARK: - Field Parsing (manifest mode)

private func parseFieldArray(_ arr: [JSONValue]) -> [FieldMeta] {
    arr.compactMap { v -> FieldMeta? in
        guard let name = v["name"]?.stringValue else { return nil }
        let typeStr = v["type"]?.stringValue ?? v["fieldType"]?.stringValue ?? "string"
        let fieldType = parseFieldType(typeStr, v: v)
        let required = v["required"]?.boolValue ?? false
        let description = v["description"]?.stringValue
        return FieldMeta(
            name: name,
            description: description,
            fieldType: fieldType,
            required: required
        )
    }
}

private func parseFieldType(_ raw: String, v: JSONValue) -> FieldType {
    switch raw {
    case "number", "integer": return .number
    case "boolean": return .boolean
    case "array":
        let inner = v["items"]?["type"]?.stringValue ?? "string"
        return .array(parseFieldType(inner, v: v["items"] ?? .null))
    case "enum":
        let values = (v["values"]?.arrayValue ?? []).compactMap { $0.stringValue }
        return .enum(values)
    default:
        return .string
    }
}

// MARK: - Rendering

func renderSwiftSource(cliName: String, entries: [TypegenEntry]) -> String {
    var lines: [String] = []
    lines.append("// Generated by IncurGen. Do not edit by hand.")
    lines.append("// Source: \(cliName)")
    lines.append("")
    lines.append("import Foundation")
    lines.append("import Incur")
    lines.append("")
    lines.append("public enum IncurGenerated {")
    lines.append("    public static let cliName = \(quoted(cliName))")
    lines.append("")

    if entries.isEmpty {
        lines.append("    // No registered commands.")
    }

    for entry in entries {
        lines.append(contentsOf: renderEntry(entry))
        lines.append("")
    }

    lines.append("}")
    lines.append("")
    return lines.joined(separator: "\n")
}

private func renderEntry(_ entry: TypegenEntry) -> [String] {
    let typeName = swiftTypeName(from: entry.fullName)
    var out: [String] = []
    out.append("    /// `\(entry.fullName)`")
    out.append("    public enum \(typeName) {")
    out.append("        public static let name = \(quoted(entry.fullName))")
    out.append("")
    // CTA function
    let params = ctaParams(args: entry.argsFields, options: entry.optionsFields)
    let body = ctaBody(commandName: entry.fullName, args: entry.argsFields, options: entry.optionsFields)
    out.append("        /// Build a CTA invocation string for this command.")
    out.append("        public static func cta(\(params)) -> String {")
    for line in body {
        out.append("            \(line)")
    }
    out.append("        }")
    out.append("    }")
    return out
}

// MARK: - Helpers

private func ctaParams(args: [FieldMeta], options: [FieldMeta]) -> String {
    var params: [String] = []
    for f in args {
        let swiftType = swiftType(for: f.fieldType)
        if f.required {
            params.append("\(swiftIdentifier(f.name)): \(swiftType)")
        } else {
            params.append("\(swiftIdentifier(f.name)): \(swiftType)? = nil")
        }
    }
    for f in options {
        let swiftType = swiftType(for: f.fieldType)
        params.append("\(swiftIdentifier(f.name)): \(swiftType)? = nil")
    }
    return params.joined(separator: ", ")
}

private func ctaBody(commandName: String, args: [FieldMeta], options: [FieldMeta]) -> [String] {
    var lines: [String] = []
    lines.append("var parts: [String] = [\(quoted(commandName))]")
    for f in args {
        let id = swiftIdentifier(f.name)
        if f.required {
            lines.append("parts.append(\"\\(\(id))\")")
        } else {
            lines.append("if let v = \(id) { parts.append(\"\\(v)\") }")
        }
    }
    for f in options {
        let id = swiftIdentifier(f.name)
        let cliName = f.cliName
        lines.append("if let v = \(id) { parts.append(\"--\(cliName) \\(v)\") }")
    }
    lines.append("return parts.joined(separator: \" \")")
    return lines
}

private func swiftType(for ft: FieldType) -> String {
    switch ft {
    case .string, .enum, .value: return "String"
    case .number, .count: return "Double"
    case .boolean: return "Bool"
    case .array(let inner): return "[\(swiftType(for: inner))]"
    }
}

private func swiftTypeName(from path: String) -> String {
    // "pr review approve" -> "PrReviewApprove"
    let parts = path.split(whereSeparator: { !$0.isLetter && !$0.isNumber })
    return parts.map { piece -> String in
        guard let first = piece.first else { return "" }
        return first.uppercased() + piece.dropFirst()
    }.joined()
}

private func swiftIdentifier(_ name: String) -> String {
    // Convert kebab-case or snake_case to lowerCamelCase, escape Swift keywords.
    let lowered = name.lowercased()
    var result = ""
    var nextUpper = false
    for ch in lowered {
        if ch == "-" || ch == "_" {
            nextUpper = true
        } else if nextUpper {
            result.append(Character(ch.uppercased()))
            nextUpper = false
        } else {
            result.append(ch)
        }
    }
    if swiftReservedWords.contains(result) {
        return "`\(result)`"
    }
    return result
}

private let swiftReservedWords: Set<String> = [
    "class", "struct", "enum", "func", "var", "let", "if", "else", "switch",
    "case", "default", "for", "while", "return", "true", "false", "nil",
    "import", "public", "private", "internal", "fileprivate", "open",
    "static", "final", "self", "init", "deinit", "extension", "protocol",
    "where", "guard", "throw", "throws", "try", "catch", "do", "defer",
    "in", "as", "is", "any", "some", "Type", "associatedtype", "operator",
]

private func quoted(_ s: String) -> String {
    let escaped = s
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}
